<script>

    Ext.onReady(function() {
        Ext.QuickTips.init();
        var Form = Ext.create('Ext.form.Panel', {
            border: false,
            bodyBorder: false,
            bodyPadding: '10 10 5 10',
            defaultType: 'textfield',
            defaults: {
                anchor: '100%',
                msgTarget: 'under',
                padding: '5px 0'
            },
            frame: false,
            renderTo: Ext.getBody(),
            style: 'margin:50 auto 0 auto;',
            url: '/register',
            waitMsgTarget: true,
            width: 400,
            items: [
                /*Username label*/
                {
                    xtype: 'label',
                    text: 'Nome de utilizador'
                },
                /*Username field*/
                {
                    name: 'username'
                    
                },
                /*E-mail abel*/
                {
                    xtype: 'label',
                    text: 'E-mail'
                },
                /*E-mail field*/
                {
                    name: 'email'
                },
                /*Password label*/
                {
                    xtype: 'label',
                    text: 'Palavra-passe'
                },
                /*Password field container*/
                {
                    xtype: 'fieldcontainer',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            name: 'password',
                            flex: 1,
                            inputType: 'password',
                            msgTarget: 'under'
                        },
                        {
                            xtype: 'button',
                            text: 'Mostrar',
                            style: 'border-top-left-radius:0 !important;border-bottom-left-radius:0 !important;',
                            handler: function() {
                                return;
                                this.setText('Esconder');
                            }
                        }
                    ]
                },
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        pack: 'start'
                    },
                    padding: '10',
                    width: 400,
                    items: [
                        /* Create account button */
                        {
                            xtype: 'button',
                            disabled: true,
                            formBind: true,
                            scale: 'medium',
                            text: 'Criar a minha conta',
                            width: 100,
                            handler: function() {
                                /* Normally we would submit the form to the server here and handle the response...*/
                                Form.submit({
                                    clientValidation: false,
                                    submitEmptyText: false,
                                    waitMsg: 'Aguarde...',
                                    success: function(form, action) {
                                        window.location = '/register/success';
                                    },
                                    failure: function(form, action) {
                                    }
                                });
                            }
                        },
                        /* Some space */
                        {
                            xtype: 'tbspacer',
                            height: 10
                        },
                        /*Terms & Conditions*/
                        {
                            xtype: 'box',
                            pack: 'center',
                            html: 'Ao clicar em "Criar conta" está a concordar com os nossos <a href="/terms-of-service" target="_blank">termos de serviço</a> e <a href="/privacy-policy">politicas de privacidade</a>.',
                        }
                    ]
                }]
        });
    });

</script>