<script>

    Ext.onReady(function() {
        var Form = Ext.create('Ext.form.Panel', {
            border: false,
            bodyBorder: false,
            bodyPadding: '10 10 5 10',
            defaultType: 'textfield',
            defaults: {
                anchor: '100%',
                msgTarget: 'under',
                padding: '5px 0'
            },
            frame: false,
            renderTo: Ext.getBody(),
            style: 'margin:50 auto 0 auto;',
            url: '/register',
            waitMsgTarget: true,
            width: 400,
            items: [
                /*E-mail abel*/
                {
                    xtype: 'label',
                    text: 'E-mail'
                },
                /*E-mail textfield*/
                {
                    name: 'email'
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'top',
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        pack: 'start'
                    },
                    items: [
                        {
                            xtype: 'box',
                            html: 'Introduza o seu e-mail para recuperar a palavra-passe',
                            padding: 10,
                            style: 'font-size:14px;'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    dock: 'bottom',
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        pack: 'start'
                    },
                    padding: '10',
                    items: [
                        /* Create account button */
                        {
                            xtype: 'button',
                            disabled: true,
                            formBind: true,
                            scale: 'medium',
                            text: 'Recuperar palavra-passe',
                            width: 100,
                            handler: function() {
                                /* Normally we would submit the form to the server here and handle the response...*/
                                Form.submit({
                                    clientValidation: false,
                                    submitEmptyText: false,
                                    waitMsg: 'Aguarde...',
                                    success: function(form, action) {
                                        window.location = '/register/success';
                                    },
                                    failure: function(form, action) {
                                    }
                                });
                            }
                        },
                        /* Some space */
                        {
                            xtype: 'tbspacer',
                            height: 10
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'start'
                            },
                            items: [
                                {
                                    xtype: 'box',
                                    html: '<a href="/register">Criar uma conta</a>'
                                },
                                {
                                    xtype: 'box',
                                    html: '·',
                                    padding: '0 10 0 10'
                                },
                                {
                                    xtype: 'box',
                                    html: '<a href="/login">Entrar na conta</a>'
                                }
                            ]
                        }
                    ]
                }]
        });
    });

</script>