<!-- WOWWWWW HTML5, these developers has good skills :P -->
<!DOCTYPE>

<!-- How ✆ To ➳ Meet ❤ Ladies ♀ (HTML) -->
<html>

    <!-- ☺ Head'Shot ... Counter-Strike ... Good old times -->
    <head>

        <!-- utf-0x10 >> 1 - if u like bitwise operators xD -->
        <meta charset="utf-8">

        <!-- Ext-JS - Oh, look at me, I have some Styles :D -->
        <link rel="stylesheet" type="text/css" href="/js/ext-js/resources/ext-theme-neptune/ext-theme-neptune-all.css">
        <!--<link rel="stylesheet" type="text/css" href="/resources/css/bootstrap/bootstrap.css">-->

        <!-- Ext-JS - Oh, look at me, I have some scripts and I hate IE browsers ☢ -->
        <script type="text/javascript" src="/js/ext-js/ext-all.js"></script>

    </head>

    <!-- My face before catching a tan -> ☺ -->
    <!-- My face after catching a tan -> ☻ -->
    <!-- I really love going to the beach in the summer to get a tan on my body ☀ -->
    <body>
        <?php echo $this->layout()->content; ?>
    </body>

</html>