<script>

    Ext.Loader.setConfig({enabled: true});

    Ext.Loader.setPath('Ext.ux', '/js/ext-js/examples/ux/');
    Ext.require([
        'Ext.grid.*',
        'Ext.data.*',
        'Ext.util.*',
        'Ext.toolbar.Paging',
        'Ext.ux.grid.FiltersFeature',
        'Ext.ux.PreviewPlugin',
        'Ext.ux.ProgressBarPager',
        'Ext.ModelManager',
        'Ext.tip.QuickTipManager'
    ]);

    Ext.onReady(function() {

        var filters = {
            ftype: 'filters',
            encode: true, // json encode the filter query
            local: false, // defaults to false (remote filtering)
            filters: [
                {
                    type: 'boolean',
                    dataIndex: 'visible'
                }
            ]
        };

        var store = new Ext.data.JsonStore({
            autoLoad: true,
            fields: ['id', 'confirmed', 'email', 'name'],
            pageSize: 1,
            proxy: {
                type: 'ajax',
                url: '/api/senders',
                reader: {
                    root: 'data.items',
                    id: 'sender_id',
                    totalProperty: 'data.totalItems'
                },
                simpleSortMode: true
            },
            remoteSort: true
        });

        // create the grid
        SendersGrid = Ext.create('Ext.grid.Panel', {
            bbar: {
                xtype: 'pagingtoolbar',
                store: store,
                displayInfo: true,
                plugins: new Ext.ux.ProgressBarPager()
            },
            columns: [
                {
                    text: 'Endereço de e-mail',
                    dataIndex: 'email',
                    filterable: true,
                    flex: 1,
                    menuDisabled: false,
                    resizable: false,
                    sortable: true
                },
                {
                    text: 'Nome',
                    dataIndex: 'name',
                    filterable: true,
                    flex: 1,
                    menuDisabled: false,
                    resizable: false,
                    sortable: true
                },
                {
                    text: 'Confirmado',
                    dataIndex: 'confirmed',
                    filterable: true,
                    menuDisabled: false,
                    resizable: false,
                    sortable: false,
                    width: 200
                }
            ],
            features: [filters],
            flex: 1,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    items: [
                        {
                            text: 'Adicionar remetente',
                            handler: function() {
                                App.app.getController('Senders').create();
                            }
                        }
                    ]
                }
            ],
            padding: 20,
            store: store,
            stripeRows: true,
            titleAlign: 'left',
            title: 'Remetentes',
            viewConfig: {
                loadingText: 'A carregar...'
            },
            xtype: 'progress-bar-pager'
        });

        Layout.add(SendersGrid);

    });

</script>